apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: es-client
  namespace: {{ .Release.Namespace }}
  labels:
    component: elasticsearch
    role: client
    nodename: es_client
spec:
  replicas: {{ .Values.es_client.replicas | default 3 }}
  selector:
    matchLabels:
      component: elasticsearch
      role: client
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
      annotations:
        checksum/es-config: {{ include (print $.Template.BasePath "/config/config.yaml") . | sha256sum }}
        {{- include "annotations" .Values }}
    spec:
      serviceAccount: elasticsearch
      serviceAccountName: elasticsearch
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{- range $key, $val := .Values.es_cluster.env_var }}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
{{- end }}
{{- range $key, $val := .Values.es_client.env_var }}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
{{- end }}
{{- if .Values.es_client.container }}
        resources:
{{- end }}
{{- if .Values.es_client.container.limit }}
          limits:
            memory: {{ .Values.es_client.container.limit.mem | quote }}
            cpu: {{ .Values.es_client.container.limit.cpu | quote }}
{{- end }}
{{- if .Values.es_client.container.request }}
          requests:
            memory: {{ .Values.es_client.container.request.mem | quote }}
            cpu: {{ .Values.es_client.container.request.cpu | quote }}
{{- end }}
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        readinessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 120
          periodSeconds: 15
      volumes:
        - name: es-config
          configMap:
            name: es-configmap
        - emptyDir:
            medium: ""
          name: "storage"
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
